; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:yolo_uno]
platform = espressif32
board = yolo_uno
framework = arduino
monitor_speed = 115200

; Thư viện đèn LED của bà
lib_deps = 
    adafruit/Adafruit NeoPixel @ ^1.12.0

; TỔNG HỢP BUILD FLAGS CỦA CẢ 2 NGƯỜI
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -DEI_CLASSIFIER_TFLITE_ENABLE_ESP_NN=0
    -DEI_CLASSIFIER_ENABLE_ESP_NN=0
    -DEI_CLASSIFIER_ENABLE_CMSIS_NN=0

; BỘ LỌC CHỐNG LỖI AI CỦA CHỊ THẢO
build_src_filter =
    +<*>
    -<lib/Final_Project_inferencing/src/edge-impulse-sdk/porting/espressif/ESP-NN/>